name: Release CLI

on:
  push:
    tags:
      - 'cli-v*'  # Trigger on tags like cli-v2.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS ARM64 (M1/M2/M3)
          - os: macos-latest
            target: aarch64-apple-darwin
            name: promptguard-macos-arm64

          # macOS x86_64 (Intel)
          - os: macos-latest
            target: x86_64-apple-darwin
            name: promptguard-macos-x86_64

          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: promptguard-linux-x86_64

          # Linux ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: promptguard-linux-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build CLI
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary
        run: |
          cd target/${{ matrix.target }}/release
          cp promptguard ${{ matrix.name }}
          chmod +x ${{ matrix.name }}

          # Generate checksum
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            shasum -a 256 ${{ matrix.name }} > ${{ matrix.name }}.sha256
          else
            sha256sum ${{ matrix.name }} > ${{ matrix.name }}.sha256
          fi

          # Move to workspace root
          mv ${{ matrix.name }} $GITHUB_WORKSPACE/
          mv ${{ matrix.name }}.sha256 $GITHUB_WORKSPACE/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ matrix.name }}
            ${{ matrix.name }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find artifacts -type f -exec cp {} release/ \;
          ls -lah release/

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/cli-v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: PromptGuard CLI v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## PromptGuard CLI v${{ steps.get_version.outputs.VERSION }}

            Drop-in LLM security for your applications - Built with Rust + Tree-sitter

            ### Installation

            **One-line install (macOS/Linux)**:
            ```bash
            curl -fsSL https://raw.githubusercontent.com/acebot712/promptguard-cli/main/install.sh | sh
            ```

            **Manual install**:
            1. Download the binary for your platform below
            2. Make it executable: `chmod +x promptguard-*`
            3. Move to PATH: `sudo mv promptguard-* /usr/local/bin/promptguard`
            4. Verify: `promptguard --version`

            ### Checksums

            SHA256 checksums are provided for each binary (`.sha256` files).

            ### What's New

            - ✅ Real AST transformations using Tree-sitter
            - ✅ TypeScript, JavaScript, Python support
            - ✅ OpenAI, Anthropic, Cohere, HuggingFace providers
            - ✅ Automatic backups with safe revert
            - ✅ Single 5.3MB static binary

            ### Supported Platforms

            - macOS ARM64 (M1/M2/M3)
            - macOS x86_64 (Intel)
            - Linux x86_64
            - Linux ARM64

            ---

            📖 **Documentation**: https://docs.promptguard.co/cli
            🏠 **Homepage**: https://promptguard.co
            🐛 **Issues**: https://github.com/acebot712/promptguard-cli/issues
          files: release/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
